apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: $newapp_name
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: $newapp_name
          image: '$IMAGE'
          resources:
            requests:
              cpu: 10m
              memory: 10M
          env: []
          envFrom: []
          command: []
          volumeMounts: []
      volumes: []
      hostNetwork: false
    metadata:
      labels:
        service.alauda.io/name: statefulset-$newapp_name
      annotations:
        cni.projectcalico.org/ipAddrs: '["$subnet_ip"]'
  strategy:
    type: OnDelete
  serviceName: $newapp_name

