apiVersion: v1
kind: Secret
metadata:
  name: $secret_name
  annotations:
     alauda.io/displayName: $secret_displayname
     alauda.io/product: Alauda Cloud Enterprise
  namespace: ""
type: kubernetes.io/basic-auth
data:
  username: $GIT_USERNAME
  password: $GIT_PASSWORD
