kind: StorageClass
parameters:
  clusterNamespace: rook-ceph
  pool: replicapool
apiVersion: storage.k8s.io/v1
reclaimPolicy: Delete
provisioner: ceph.rook.io/block
metadata:
  name: $scs_name
  annotations:
    storageclass.kubernetes.io/is-default-class: '$is_default'